/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import Successfull.noAccount;
import config.Session;
import config.dbConnect;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author alcay
 */
public class userChangepass extends javax.swing.JFrame {

    /**
     * Creates new form userChangepass
     */
    public userChangepass() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submit = new rojerusan.RSMaterialButtonCircle();
        cancel = new rojerusan.RSMaterialButtonCircle();
        jLabel9 = new javax.swing.JLabel();
        confirmPass = new textfield.PasswordField();
        jLabel2 = new javax.swing.JLabel();
        id = new rojerusan.RSMaterialButtonCircle();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        oldPass = new textfield.TextField();
        newPass = new textfield.TextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setBackground(new java.awt.Color(255, 51, 51));
        submit.setText("SUBMIT");
        submit.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 390, 60));

        cancel.setBackground(new java.awt.Color(204, 204, 255));
        cancel.setForeground(new java.awt.Color(51, 51, 51));
        cancel.setText("CANCEL");
        cancel.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 390, 60));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Do you want to Cancel?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, 30));

        confirmPass.setBackground(new java.awt.Color(204, 255, 255));
        confirmPass.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        confirmPass.setLabelText("Confirm your Password");
        confirmPass.setShowAndHide(true);
        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("Change your Password Here!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("  X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 40));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 40));

        oldPass.setBackground(new java.awt.Color(204, 255, 255));
        oldPass.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        oldPass.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        oldPass.setLabelText("Enter your Old Password");
        oldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassActionPerformed(evt);
            }
        });
        jPanel1.add(oldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 330, 60));

        newPass.setBackground(new java.awt.Color(204, 255, 255));
        newPass.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        newPass.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        newPass.setLabelText("Enter your New Password");
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 330, 60));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/new.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/confirm.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 60));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/pass.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 60));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel4.setText("CHANGE PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked

    }//GEN-LAST:event_submitMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    try {
    dbConnect connect = new dbConnect();
    Session sess = Session.getInstance();

    String query = "SELECT password FROM users WHERE p_id = ?";
    try (PreparedStatement pst = connect.getConnection().prepareStatement(query)) {
        pst.setInt(1, sess.getPid());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String oldPassHash = rs.getString("password");
            String oldPassInputHash = passwordHasher.hashPassword(oldPass.getText());

            if (oldPassHash.equals(oldPassInputHash)) {
                String newPassword = newPass.getText();
                String confirmPassword = confirmPass.getText();

                if (newPassword.length() < 8) {
                    JOptionPane.showMessageDialog(null, "New password must be at least 8 characters long!");
                } else if (!newPassword.equals(confirmPassword)) {
                    JOptionPane.showMessageDialog(null, "New password and confirm password do not match!");
                } else {
                    String newPassHash = passwordHasher.hashPassword(newPassword);

                    String updateQuery = "UPDATE users SET password = ? WHERE p_id = ?";
                    try (PreparedStatement updatePst = connect.getConnection().prepareStatement(updateQuery)) {
                        updatePst.setString(1, newPassHash);
                        updatePst.setInt(2, sess.getPid());
                        int rowsUpdated = updatePst.executeUpdate();

                        if (rowsUpdated > 0) {
                            JOptionPane.showMessageDialog(null, "Password updated successfully!");
                            userDashboard usd = new userDashboard();
                            usd.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Failed to update password!");
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Old password is incorrect!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User not found!");
        }
    }
} catch (SQLException | NoSuchAlgorithmException ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    ex.printStackTrace();
}

    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
            userForm usf =new userForm();
            usf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
       int pid = sess.getPid();
       if(sess.getPid() == 0){       
       new noAccount().setVisible(true);
       this.setVisible(false);
       this.dispose();
       }else{
           id.setText(""+sess.getPid());
           
           
          
       }
    }//GEN-LAST:event_formWindowActivated

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      userForm usf = new userForm();
      usf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userChangepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userChangepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userChangepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userChangepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userChangepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle cancel;
    private textfield.PasswordField confirmPass;
    private rojerusan.RSMaterialButtonCircle id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public textfield.TextField newPass;
    public textfield.TextField oldPass;
    private rojerusan.RSMaterialButtonCircle submit;
    // End of variables declaration//GEN-END:variables
}
