/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import Successfull.registerSuccess;
import config.dbConnect;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author alcay
 */
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    public registerUser() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
public boolean duplicateCheck() {
    dbConnect dbc = new dbConnect();
    try {
        String query = "SELECT * FROM users WHERE username = '" + un.getText() + "' OR email = '" + em.getText() + "'";
        ResultSet resultSet = dbc.getData(query);

        if (resultSet.next()) {
            String email = resultSet.getString("email");
            if (email.equals(em.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already used");
                em.setText("");
            }
            String username = resultSet.getString("username");
            if (username.equals(un.getText())) { //Error: You were comparing username with email's text field. changed to un1's text field
                JOptionPane.showMessageDialog(null, "Username is Already used"); //Error: Changed the message to reflect username duplication
                un.setText("");
            }
            return true;
        } else {
            return false;
        }
    } catch (SQLException ex) {
        System.out.println("" + ex);
        return false;
    }
}
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        login = new rojerusan.RSMaterialButtonCircle();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        un = new textfield.TextField();
        fn = new textfield.TextField();
        ct = new textfield.TextField();
        em = new textfield.TextField();
        cn = new textfield.TextField();
        Signup = new rojerusan.RSMaterialButtonCircle();
        ps = new textfield.PasswordField();
        utype = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Do you have an account?Login");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 780, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("SIGN UP PAGE");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Create New Account Here");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 30));

        login.setBackground(new java.awt.Color(204, 204, 255));
        login.setForeground(new java.awt.Color(51, 51, 51));
        login.setText("LOG IN");
        login.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, 390, 60));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/pass.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, 60));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("  X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        un.setBackground(new java.awt.Color(204, 255, 255));
        un.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        un.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        un.setLabelText("Enter your Username");
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 330, 60));

        fn.setBackground(new java.awt.Color(204, 255, 255));
        fn.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        fn.setLabelText("Enter your Full Name");
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 330, 60));

        ct.setBackground(new java.awt.Color(204, 255, 255));
        ct.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ct.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        ct.setLabelText("Enter your City and Address");
        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });
        jPanel1.add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 330, 60));

        em.setBackground(new java.awt.Color(204, 255, 255));
        em.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        em.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        em.setLabelText("Enter your Email");
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 330, 60));

        cn.setBackground(new java.awt.Color(204, 255, 255));
        cn.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cn.setLabelText("Enter your Contact No");
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 330, 60));

        Signup.setBackground(new java.awt.Color(255, 51, 51));
        Signup.setText("SIGN UP");
        Signup.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 390, 60));

        ps.setBackground(new java.awt.Color(204, 255, 255));
        ps.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        ps.setLabelText("Enter your Password");
        ps.setShowAndHide(true);
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 330, 60));

        utype.setBackground(new java.awt.Color(204, 255, 255));
        utype.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Type : ", "Admin", "Patient", "Doctor" }));
        utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypeActionPerformed(evt);
            }
        });
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 150, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/user.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, 60));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/cnn.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 60));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/emm.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/images-24-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/full.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utypeActionPerformed

    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
        registerSuccess reg = new registerSuccess();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignupMouseClicked

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        if (fn.getText().isEmpty() || ct.getText().isEmpty() || em.getText().isEmpty() || cn.getText().isEmpty() || un.getText().isEmpty() || ps.getText().isEmpty() || utype.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All Fields Are Required");
        } else {
            if (fn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Full Name is required");
                fn.setText("");
                return;
            }
            if (ct.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "City & Address is required");
                ct.setText("");
                return;
            }
            if (em.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Email is required");
                em.setText("");
                return;
            }

            String input = cn.getText();
            if (!input.matches("[0-9]{11}")) {
                JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits only)");
                cn.setText("");
                return;
            }

            String email = em.getText();
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            Pattern pattern = Pattern.compile(emailRegex);
            Matcher matcher = pattern.matcher(email);

            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid email ");
                em.setText("");
                return;
            }

            if (un.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Username is required");
                un.setText("");
                return;
            }

            String password = ps.getText();

            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Password is required");
                
                return;
            }
            if (password.length() < 8) {
                JOptionPane.showMessageDialog(null, "Password should have at least 8 characters");
                return;
            }

            String selectedUserType = (String) utype.getSelectedItem();
            if (!("Admin".equals(selectedUserType) || "Patient".equals(selectedUserType) || "Doctor".equals(selectedUserType))) {
                JOptionPane.showMessageDialog(null, "Please select a User Type ");
                return;
            }
            else {
                dbConnect dbc = new dbConnect();
                try{
                    String pass = passwordHasher.hashPassword(ps.getText());
                    String checkUsernameQuery = "SELECT COUNT(*) FROM users WHERE username = '" + un.getText() + "'";
                    int usernameCount = dbc.executeQueryForCount(checkUsernameQuery);
                    if (usernameCount > 0) {
                        JOptionPane.showMessageDialog(null, "Username is already taken");
                         un.setText("");

                        return;
                    }

                    String checkEmailQuery = "SELECT COUNT(*) FROM users WHERE email = '" + em.getText() + "'";
                    int emailCount = dbc.executeQueryForCount(checkEmailQuery);
                    if (emailCount > 0) {
                        JOptionPane.showMessageDialog(null, "Email is already registered");
                        em.setText("");

                        return;
                    }

                    String insertQuery = "INSERT INTO users(fn, cityAddress, email, contactNo, username, password, usertype, status) " +
                    "VALUES('" + fn.getText() + "', '" + ct.getText() + "', '" + em.getText() + "', '" + cn.getText() + "', '" + un.getText() + "', '" + pass + "', '" + selectedUserType + "', 'Pending')";

                    if (dbc.insertData(insertQuery) == 0) {
                        
                    }
                    new registerSuccess().setVisible(true);
                    this.setVisible(false);
                    this.dispose();
                    

                }catch(NoSuchAlgorithmException ex){
                    System.out.println(""+ex);
                }
            }
            
        }
                
    }//GEN-LAST:event_SignupActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        Main mn = new Main();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Signup;
    private textfield.TextField cn;
    private textfield.TextField ct;
    private textfield.TextField em;
    private textfield.TextField fn;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSMaterialButtonCircle login;
    private textfield.PasswordField ps;
    private textfield.TextField un;
    public javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
