/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import Successfull.registerSuccess;
import config.Session;
import config.dbConnect;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author alcay
 */
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    public registerUser() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public static String email,username;
public boolean duplicateCheck() {
    dbConnect dbc = new dbConnect();
    try {
        String query = "SELECT * FROM users WHERE username = '" + answer.getText() + "' OR email = '" + em.getText() + "'";
        ResultSet resultSet = dbc.getData(query);

        if (resultSet.next()) {
            String email = resultSet.getString("email");
            if (email.equals(em.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already used");
                em.setText("");
            }
            String username = resultSet.getString("username");
            if (username.equals(answer.getText())) { 
                JOptionPane.showMessageDialog(null, "Username is Already used"); 
                answer.setText("");
            }
            return true;
        } else {
            return false;
        }
    } catch (SQLException ex) {
        System.out.println("" + ex);
        return false;
    }
}
    public void logEvent(int userId, String username, String description) {
    dbConnect dbc = new dbConnect();
    Connection con = dbc.getConnection();
    PreparedStatement pstmt = null;

    try {
        // Fixed: include `log_description` in your INSERT
        String sql = "INSERT INTO tbl_log (p_id, u_username, login_time, u_type, log_status) VALUES (?, ?, ?, ?, ?)";
        pstmt = con.prepareStatement(sql);

        pstmt.setInt(1, userId);
        pstmt.setString(2, username);
        pstmt.setTimestamp(3, new Timestamp(new Date().getTime())); // login_time
        pstmt.setString(4, "Success - User Action"); // u_type (general category)
        pstmt.setString(5, "Active"); // log_status

        pstmt.executeUpdate();
        System.out.println("Log event recorded successfully.");
    } catch (SQLException e) {
        System.out.println("Error recording log: " + e.getMessage());
    } finally {
        try {
            if (pstmt != null) pstmt.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error closing resources: " + e.getMessage());
        }
    }
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        answer = new textfield.TextField();
        fn = new textfield.TextField();
        ct = new textfield.TextField();
        em = new textfield.TextField();
        cn = new textfield.TextField();
        Signup = new rojerusan.RSMaterialButtonCircle();
        ps = new textfield.PasswordField();
        utype = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        securityQ = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        un = new textfield.TextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 36), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Do you have an account?Login");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 890, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("SIGN UP PAGE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/pass.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, 60));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("  X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 30));

        answer.setBackground(new java.awt.Color(204, 255, 255));
        answer.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        answer.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        answer.setLabelText("Enter your Answer");
        jPanel1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 330, 60));

        fn.setBackground(new java.awt.Color(204, 255, 255));
        fn.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        fn.setLabelText("Enter your Full Name");
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 330, 60));

        ct.setBackground(new java.awt.Color(204, 255, 255));
        ct.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ct.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        ct.setLabelText("Enter your City and Address");
        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });
        jPanel1.add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 330, 60));

        em.setBackground(new java.awt.Color(204, 255, 255));
        em.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        em.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        em.setLabelText("Enter your Email");
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 330, 60));

        cn.setBackground(new java.awt.Color(204, 255, 255));
        cn.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cn.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cn.setLabelText("Enter your Contact No");
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 330, 60));

        Signup.setBackground(new java.awt.Color(255, 51, 51));
        Signup.setText("SIGN UP");
        Signup.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        jPanel1.add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 820, 390, 60));

        ps.setBackground(new java.awt.Color(204, 255, 255));
        ps.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        ps.setLabelText("Enter your Password");
        ps.setShowAndHide(true);
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        jPanel1.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 330, 60));

        utype.setBackground(new java.awt.Color(204, 255, 255));
        utype.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Type : ", "Admin", "Patient" }));
        utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypeActionPerformed(evt);
            }
        });
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 780, 150, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/user.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, 60));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/cnn.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, 60));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/emm.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/images-24-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardImage/full.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 60));

        securityQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your Nickname?", "What is your favourite movie?", "What is your favourite food?" }));
        securityQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQActionPerformed(evt);
            }
        });
        jPanel1.add(securityQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, 330, 50));

        jLabel1.setText("Security Question :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, -1, -1));

        un.setBackground(new java.awt.Color(204, 255, 255));
        un.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        un.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        un.setLabelText("Enter your Username");
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 330, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Create New Account Here");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utypeActionPerformed

    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
        registerSuccess reg = new registerSuccess();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignupMouseClicked

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
  // Store dropdown selections first
String selectedUserType = (String) utype.getSelectedItem();
String selectedSecurityQ = (String) securityQ.getSelectedItem();

// Ensure all fields are filled and dropdowns are not default/blank
if (fn.getText().trim().isEmpty() || ct.getText().trim().isEmpty() || em.getText().trim().isEmpty() ||
    cn.getText().trim().isEmpty() || un.getText().trim().isEmpty() || ps.getText().trim().isEmpty() ||
    selectedUserType == null || selectedUserType.trim().equals("") || selectedUserType.equals("Select") ||
    selectedSecurityQ == null || selectedSecurityQ.trim().equals("") || selectedSecurityQ.equals("Select") ||
    answer.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All Fields Are Required!");

} else if (!(selectedUserType.equals("Admin") || selectedUserType.equals("Patient"))) {
    JOptionPane.showMessageDialog(null, "Invalid user type selected.");
    
} else if (ps.getText().length() < 8) {
    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters.");
    ps.setText("");

} else if (!em.getText().matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")) {
    JOptionPane.showMessageDialog(null, "Enter a valid email address.");
    em.setText("");

} else if (!cn.getText().matches("\\d{11}")) {
    JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits).");
    cn.setText("");

} else if (duplicateCheck()) {
    JOptionPane.showMessageDialog(null, "Duplicate entry detected!");

} else {
    dbConnect dbc = new dbConnect();
    Session sess = Session.getInstance();
    int userId = sess.getPid();

    try {
        String hashedPassword = passwordHasher.hashPassword(ps.getText()); // ✅ Hash the password
        String status = selectedUserType.equalsIgnoreCase("Admin") ? "Approved" : "Pending";
        String query = "INSERT INTO users(fn, cityAddress, email, contactNo, username, password, usertype, securityQ, answer, status, image) " +
                       "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'Pending', 'NULL')";

        try (Connection con = dbc.getConnection(); 
             PreparedStatement stmt = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, fn.getText().trim());
            stmt.setString(2, ct.getText().trim());
            stmt.setString(3, em.getText().trim());
            stmt.setString(4, cn.getText().trim());
            stmt.setString(5, un.getText().trim());
            stmt.setString(6, hashedPassword);
            stmt.setString(7, selectedUserType);
            stmt.setString(8, selectedSecurityQ);
            stmt.setString(9, answer.getText().trim());

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                try (ResultSet rs = stmt.getGeneratedKeys()) {
                    if (rs.next()) {
                        logEvent(userId, un.getText(), "New user registered: " + un.getText());
                        JOptionPane.showMessageDialog(null, "Registration Successful!");
                        new registerSuccess().setVisible(true);
                        this.dispose();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Registration Failed. Try again!");
            }
        }
    } catch (SQLException | NoSuchAlgorithmException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
}





    
                
    }//GEN-LAST:event_SignupActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctActionPerformed

    private void securityQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQActionPerformed
     
    }//GEN-LAST:event_securityQActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        Main mn = new Main();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
Main mn = new Main();
mn.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Signup;
    private textfield.TextField answer;
    private textfield.TextField cn;
    private textfield.TextField ct;
    private textfield.TextField em;
    private textfield.TextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private textfield.PasswordField ps;
    private javax.swing.JComboBox<String> securityQ;
    private textfield.TextField un;
    public javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
