/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import config.dbConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JPasswordField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author alcay
 */
public class addpatient extends javax.swing.JFrame {

    /**
     * Creates new form addpatient
     */
    public addpatient() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        displayData();
    }
       Color hover = new Color (102,102,102);
        Color defaultcolor = new Color (51,51,51);
        
        public void displayData() {
        try {
            dbConnect dbc = new dbConnect();
            ResultSet rs = dbc.getData("SELECT p_id,fn,cityAddress,email,username,usertype FROM patient");
            table2.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Errors: " + ex.getMessage());
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        utype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/weweew-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("HOSPITAL BILLS");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Full Name", "City & Address", "DateofBirth", "Email", "Contact No.", "Username", "Password", "Usertype"
            }
        ));
        jScrollPane1.setViewportView(table2);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 450, 590));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTERED OVERVIEW ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 480, 620));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel13.setText("ADD NEW PATIENT");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 460, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 15)); // NOI18N
        jLabel8.setText("Please enter your personal info!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 220, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel18.setText("Patient Full Name :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 110, 20));

        fn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 370, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel6.setText("City & Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 20));

        ct.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });
        jPanel1.add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 370, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel5.setText("Date of Birth :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 20));

        dt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        dt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 370, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 20));

        em.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        em.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 370, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel3.setText("Contact No. :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 20));

        cn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 370, 40));

        login.setBackground(new java.awt.Color(51, 51, 51));
        login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Submit");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 370, 40));

        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Usertype :", "Doctor", "Staff", "Patient" }));
        utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypeActionPerformed(evt);
            }
        });
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 370, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel4.setText("User Type :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 130, 20));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eyeee.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        icon1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                icon1KeyPressed(evt);
            }
        });
        jPanel1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 70, 40));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eyehide.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        jPanel1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 70, 60));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 370, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel10.setText("Enter Password :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 170, 20));

        un.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        un.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        un.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unKeyReleased(evt);
            }
        });
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 370, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel9.setText("Enter Username :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 170, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Already have an account ?Login");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctActionPerformed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(hover);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(defaultcolor);
    }//GEN-LAST:event_loginMouseExited

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        if (fn.getText().isEmpty() || ct.getText().isEmpty() || dt.getText().isEmpty() || em.getText().isEmpty() || cn.getText().isEmpty() || un.getText().isEmpty() || pass.getPassword().length == 0 || utype.getSelectedItem() == null || utype.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All Fields Are Required");
        } else {
            // Validate individual fields
            if (fn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Full Name is required");
                fn.setText("");
                return;
            }
            if (ct.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "City & Address is required");
                ct.setText("");
                return;
            }
            if (dt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Contact Number is required");
                dt.setText("");
                return;
            }
            if (em.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Email is required");
                em.setText("");
                return;
            }

            String input = cn.getText();
            if (!input.matches("[0-9]{11}")) {
                JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits only)");
                cn.setText("");
                return;
            }

            String email = em.getText();
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            Pattern pattern = Pattern.compile(emailRegex);
            Matcher matcher = pattern.matcher(email);

            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(null, "Please enter a valid email ");
                em.setText("");
                return;
            }

            if (un.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Username is required");
                un.setText("");
                return;
            }

            JPasswordField passwordField = (JPasswordField) pass;
            char[] passwordChars = passwordField.getPassword();

            if (passwordChars.length == 0) {
                JOptionPane.showMessageDialog(null, "Password is required");
                return;
            }
            if (passwordChars.length < 8) {
                JOptionPane.showMessageDialog(null, "Password should have at least 8 characters");
                return;
            }

            String selectedUserType = (String) utype.getSelectedItem();
            if (!("Patients".equals(selectedUserType) || "Doctors".equals(selectedUserType)|| "Staff".equals(selectedUserType) )) {
                JOptionPane.showMessageDialog(null, "Please select a User Type ");
                return;
            }

            dbConnect dbc = new dbConnect();
            String checkUsernameQuery = "SELECT COUNT(*) FROM patient WHERE username = '" + un.getText() + "'";
            int usernameCount = dbc.executeQueryForCount(checkUsernameQuery);
            if (usernameCount > 0) {
                JOptionPane.showMessageDialog(null, "Username is already taken");
                return;
            }

            String checkEmailQuery = "SELECT COUNT(*) FROM patient WHERE email = '" + em.getText() + "'";
            int emailCount = dbc.executeQueryForCount(checkEmailQuery);
            if (emailCount > 0) {
                JOptionPane.showMessageDialog(null, "Email is already registered");
                return;
            }

            String insertQuery = "INSERT INTO patient(fn, cityAddress, dateofBirth, email, contactNo, username, password, usertype, status)"
            + "VALUES('" + fn.getText() + "', '" + ct.getText() + "', '" + dt.getText() + "', '" + em.getText() + "', '" + cn.getText() + "', '" + un.getText() + "', '" + new String(passwordChars) + "', '" + selectedUserType + "', 'Pending')";

            if (dbc.insertData(insertQuery) == 0) {
                JOptionPane.showMessageDialog(null, "Registered Successfully");
                fn.setText("");
                ct.setText("");
                dt.setText("");
                em.setText("");
                cn.setText("");
                un.setText("");
                pass.setText("");
                utype.setSelectedItem("");
            }

            new adminDashboard().setVisible(true);
            this.setVisible(false);
            this.dispose();

        }
    }//GEN-LAST:event_loginActionPerformed

    private void utypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utypeActionPerformed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        icon2.setVisible(true);
        icon1.setVisible(false);
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_icon1MousePressed

    private void icon1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icon1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_icon1KeyPressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        icon1.setVisible(true);
        icon2.setVisible(false);
        pass.setEchoChar('*');
    }//GEN-LAST:event_icon2MousePressed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void unKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unKeyReleased

    }//GEN-LAST:event_unKeyReleased

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        adminDashboard adm = new adminDashboard();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
if (fn.getText().isEmpty() || ct.getText().isEmpty() || dt.getText().isEmpty() || em.getText().isEmpty() || cn.getText().isEmpty() || un.getText().isEmpty() || pass.getPassword().length == 0 || utype.getSelectedItem() == null || utype.getSelectedItem().toString().isEmpty()) {
    JOptionPane.showMessageDialog(null, "All Fields Are Required");
} else {
    // Validate individual fields
    if (fn.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Full Name is required");
        fn.setText("");
        return;
    }
    if (ct.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "City & Address is required");
        ct.setText("");
        return;
    }
    if (dt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Contact Number is required");
        dt.setText("");
        return;
    }
    if (em.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Email is required");
        em.setText("");
        return;
    }

    String input = cn.getText();
    if (!input.matches("[0-9]{11}")) {
        JOptionPane.showMessageDialog(null, "Please enter a valid contact number (11 digits only)");
        cn.setText("");
        return;
    }

    String email = em.getText();
    String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    Pattern pattern = Pattern.compile(emailRegex);
    Matcher matcher = pattern.matcher(email);

    if (!matcher.matches()) {
        JOptionPane.showMessageDialog(null, "Please enter a valid email ");
        em.setText("");
        return;
    }

    if (un.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username is required");
        un.setText("");
        return;
    }

    JPasswordField passwordField = (JPasswordField) pass;
    char[] passwordChars = passwordField.getPassword();

    if (passwordChars.length == 0) {
        JOptionPane.showMessageDialog(null, "Password is required");
        return;
    }
    if (passwordChars.length < 8) {
        JOptionPane.showMessageDialog(null, "Password should have at least 8 characters");
        return;
    }

    String selectedUserType = (String) utype.getSelectedItem();
    if (!("Patient".equals(selectedUserType) || "Doctor".equals(selectedUserType)|| "Staff".equals(selectedUserType) )) {
        JOptionPane.showMessageDialog(null, "Please select a User Type ");
        return;
    }

    dbConnect dbc = new dbConnect();
    String checkUsernameQuery = "SELECT COUNT(*) FROM patient WHERE username = '" + un.getText() + "'";
    int usernameCount = dbc.executeQueryForCount(checkUsernameQuery);
    if (usernameCount > 0) {
        JOptionPane.showMessageDialog(null, "Username is already taken");
        return;
    }

    String checkEmailQuery = "SELECT COUNT(*) FROM patient WHERE email = '" + em.getText() + "'";
    int emailCount = dbc.executeQueryForCount(checkEmailQuery);
    if (emailCount > 0) {
        JOptionPane.showMessageDialog(null, "Email is already registered");
        return;
    }

    String insertQuery = "INSERT INTO patient(fn, cityAddress, dateofBirth, email, contactNo, username, password, usertype, status)"
            + "VALUES('" + fn.getText() + "', '" + ct.getText() + "', '" + dt.getText() + "', '" + em.getText() + "', '" + cn.getText() + "', '" + un.getText() + "', '" + new String(passwordChars) + "', '" + selectedUserType + "', 'Pending')";

    if (dbc.insertData(insertQuery) == 0) {
        JOptionPane.showMessageDialog(null, "Registered Successfully");
       fn.setText("");
        ct.setText("");
        dt.setText("");
        em.setText("");
        cn.setText("");
        un.setText("");
        pass.setText("");
        utype.setSelectedItem(""); 
    }
}
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTable table2;
    private javax.swing.JTextField un;
    private javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
